// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPPIGYq0jibTJVX7hGN1vvEMnHrsFXdb0',
    appId: '1:312825292356:web:9a15f1b6c43b4d2a3abe11',
    messagingSenderId: '312825292356',
    projectId: 'smart-garden-manager',
    authDomain: 'smart-garden-manager.firebaseapp.com',
    storageBucket: 'smart-garden-manager.firebasestorage.app',
    measurementId: 'G-4RVT0RMZ77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaLKJTGeY3hekjQtEoUgyCiOVsZ7Ba4yQ',
    appId: '1:312825292356:android:3c8389c89e09909d3abe11',
    messagingSenderId: '312825292356',
    projectId: 'smart-garden-manager',
    storageBucket: 'smart-garden-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnniykUEI5iVPLGy0EEC96FLCoi795OQQ',
    appId: '1:312825292356:ios:0a18fabe7aacc85c3abe11',
    messagingSenderId: '312825292356',
    projectId: 'smart-garden-manager',
    storageBucket: 'smart-garden-manager.firebasestorage.app',
    iosBundleId: 'com.example.smartGarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnniykUEI5iVPLGy0EEC96FLCoi795OQQ',
    appId: '1:312825292356:ios:0a18fabe7aacc85c3abe11',
    messagingSenderId: '312825292356',
    projectId: 'smart-garden-manager',
    storageBucket: 'smart-garden-manager.firebasestorage.app',
    iosBundleId: 'com.example.smartGarden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPPIGYq0jibTJVX7hGN1vvEMnHrsFXdb0',
    appId: '1:312825292356:web:b73d49aa3b2c25c13abe11',
    messagingSenderId: '312825292356',
    projectId: 'smart-garden-manager',
    authDomain: 'smart-garden-manager.firebaseapp.com',
    storageBucket: 'smart-garden-manager.firebasestorage.app',
    measurementId: 'G-N0XP1TM0EB',
  );
}
